require("dotenv").config();
"use strict";
const express=require("express");
const multer=require("multer");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const db=require("./database");
const router=express.Router();
const RATES={MZN:65,AOA:950,ZAR:18.5,USD:1.02};
const FEES={TRC20:1,BEP20:.5,ERC20:5,POLYGON:.3,SOLANA:.2};
const METHODS={MZN:["MPESA","ABSA","PAYPAL"],AOA:["BANK_TRANSFER","PAYPAL"],ZAR:["PAYPAL","STANDARD_BANK","ABSA"],USD:["CARD","PAYPAL"]};
const PAYMENT_DETAILS={
 MPESA:{label:"M-Pesa",title:"M-Pesa payment",fields:["Name","Number"],values:[process.env.MPESA_NAME||"KOIN TEST",process.env.MPESA_NUMBER||"84 000 0000"],instruction:"Send the exact total shown for your order, then enter the M-Pesa transaction ID below. No screenshot is required."},
 ABSA:{label:"ABSA",title:"ABSA bank transfer",fields:["Account name","Account number","Branch"],values:[process.env.ABSA_ACCOUNT_NAME||"KOIN TEST",process.env.ABSA_ACCOUNT||"0000000000",process.env.ABSA_BRANCH||"0000"],instruction:"Make the transfer using the details above, then upload your payment proof."},
 PAYPAL:{label:"PayPal",title:"PayPal payment",fields:["PayPal email"],values:[process.env.PAYPAL_EMAIL||"payments@example.com"],instruction:"Complete the payment to the PayPal account above, then upload your payment proof."},
 BANK_TRANSFER:{label:"Multicaixa / EMIS",title:"Multicaixa / EMIS",fields:["Entity","Reference"],values:[process.env.MULTICAIXA_ENTITY||"00000",process.env.MULTICAIXA_REFERENCE||"KOIN-TEST"],instruction:"Complete the payment with the entity and reference above, then upload your payment proof."},
 STANDARD_BANK:{label:"Standard Bank",title:"Standard Bank transfer",fields:["Account name","Account number","Branch"],values:[process.env.STANDARD_BANK_ACCOUNT_NAME||"KOIN TEST",process.env.STANDARD_BANK_ACCOUNT||"0000000000",process.env.STANDARD_BANK_BRANCH||"0000"],instruction:"Make the transfer using the details above, then upload your payment proof."},
 CARD:{label:"Card",title:"Card payment",fields:["Payment page"],values:[process.env.CARD_PAYMENT_URL||"Payment gateway not configured"],instruction:"Complete the card payment through the configured gateway, then upload your payment proof."}
};
const proofDir=path.join(__dirname,"uploads","proofs");
fs.mkdirSync(proofDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,proofDir),filename:(_,file,cb)=>cb(null,Date.now()+"-"+crypto.randomBytes(6).toString("hex")+path.extname(file.originalname).toLowerCase())}),limits:{fileSize:5*1024*1024},fileFilter:(_,file,cb)=>cb(null,["image/jpeg","image/png","image/webp","application/pdf"].includes(file.mimetype))});
function ref(){return "KOIN-"+new Date().toISOString().slice(0,10).replace(/-/g,"")+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
function publicOrder(o){if(!o)return null;const copy={...o};delete copy.proofPath;delete copy.emailLog;return copy}
function validWallet(network,w){w=String(w||"").trim();if(network==="TRC20")return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(w);if(["BEP20","ERC20","POLYGON"].includes(network))return /^0x[a-fA-F0-9]{40}$/.test(w);if(network==="SOLANA")return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(w);return false}
function allowed(currency,method){return METHODS[currency]?.includes(method)}
function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
const publicUrl=()=>String(process.env.PUBLIC_URL||"http://localhost:3000").replace(/\/$/,"");
function emailLayout(title,body,reference){const statusUrl=reference?`${publicUrl()}/status.html?reference=${encodeURIComponent(reference)}`:publicUrl();return `<!doctype html><html><body style="margin:0;background:#07090d;color:#eef2f7;font-family:Arial,sans-serif;padding:30px"><div style="max-width:620px;margin:auto;background:#10151d;border:1px solid #24303c;border-radius:18px;padding:28px"><div style="font-size:24px;font-weight:800;color:#20c997">コイン</div><h1 style="font-size:25px">${esc(title)}</h1>${body}<p style="margin:24px 0"><a href="${statusUrl}" style="display:inline-block;background:#20c997;color:#03130d;text-decoration:none;font-weight:800;padding:12px 17px;border-radius:10px">Track order</a></p><p style="color:#8d97a5;font-size:12px;margin-top:28px">Automated message from コイン. You can close the website and use this link to check your order later.</p></div></body></html>`}
function orderDetailsHtml(o){return `<div style="margin:18px 0;padding:16px;background:#0b1017;border:1px solid #26323e;border-radius:12px"><p style="margin:4px 0"><b>Order:</b> ${esc(o.reference)}</p><p style="margin:4px 0"><b>Customer:</b> ${esc(o.customerName)}</p><p style="margin:4px 0"><b>Amount:</b> ${esc(o.amountUSDT)} USDT</p><p style="margin:4px 0"><b>Network:</b> ${esc(o.network)}</p><p style="margin:4px 0"><b>Network fee:</b> ${esc(o.networkFeeUSDT)} USDT</p><p style="margin:4px 0"><b>USDT price:</b> ${esc(o.unitPrice)} ${esc(o.currency)} / USDT</p><p style="margin:4px 0"><b>Total to pay:</b> ${esc(o.totalFiat)} ${esc(o.currency)}</p><p style="margin:4px 0;word-break:break-all"><b>Receiving wallet:</b> ${esc(o.walletAddress)}</p>${o.paymentMethod?`<p style="margin:4px 0"><b>Payment method:</b> ${esc(o.paymentMethod)}</p>`:""}${o.paymentReference?`<p style="margin:4px 0"><b>Payment reference:</b> ${esc(o.paymentReference)}</p>`:""}</div>`}
async function sendEmail(to,subject,html){
 const recipient=String(to||"").trim(),apiKey=String(process.env.RESEND_API_KEY||"").trim(),from=String(process.env.MAIL_FROM||"").trim();
 if(!recipient)return {sent:false,reason:"missing_recipient"};
 if(!apiKey||!from||apiKey.startsWith("re_xxxxxxxxx")){console.error("[EMAIL] NOT CONFIGURED — set a real RESEND_API_KEY and MAIL_FROM.");return {sent:false,reason:"email_not_configured"};}
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{const r=await fetch("https://api.resend.com/emails",{method:"POST",signal:controller.signal,headers:{Authorization:"Bearer "+apiKey,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject,html})});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(`Resend ${r.status}: ${data?.message||data?.error||raw||"Unknown provider error"}`);console.log(`[EMAIL] SENT to ${recipient}: ${subject} (${data.id||"no-id"})`);return {sent:true,id:data.id||null};}catch(e){const reason=e?.name==="AbortError"?"Email provider timeout after 15s":e?.message||"Unknown email error";console.error(`[EMAIL] FAILED to ${recipient}: ${reason}`);return {sent:false,reason}}finally{clearTimeout(timer)}}
function recordEmail(reference,event,result){const o=db.getOrder(reference);if(!o)return null;const log=Array.isArray(o.emailLog)?o.emailLog.slice(-19):[];log.push({event,status:result.sent?"SENT":"FAILED",id:result.id||null,error:result.sent?null:result.reason,at:new Date().toISOString()});return db.updateOrder(reference,{lastEmailStatus:result.sent?"SENT":"FAILED",lastEmailError:result.sent?null:result.reason,lastEmailAt:new Date().toISOString(),emailLog:log})}
async function notify(o,event,subject,title,body){const result=await sendEmail(o.customerEmail,subject,emailLayout(title,body,o.reference));recordEmail(o.reference,event,result);return result}
router.post("/",async(req,res)=>{const b=req.body||{},currency=String(b.currency||"").toUpperCase(),network=String(b.network||"").toUpperCase(),amount=Number(b.amountUSDT),email=String(b.customerEmail||"").trim(),name=String(b.customerName||"").trim(),wallet=String(b.walletAddress||b.wallet||"").trim();if(!RATES[currency]||!FEES[network])return res.status(400).json({success:false,message:"Currency or network is invalid."});if(!Number.isFinite(amount)||amount<10||amount>100000)return res.status(400).json({success:false,message:"Amount must be between 10 and 100,000 USDT."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({success:false,message:"A valid email is required."});if(!validWallet(network,wallet))return res.status(400).json({success:false,message:"Wallet address does not match the selected network."});const fee=FEES[network],total=(amount+fee)*RATES[currency],now=new Date().toISOString();const order={id:crypto.randomUUID(),reference:ref(),customerName:name||"Customer",customerEmail:email,amountUSDT:amount,network,networkFeeUSDT:fee,currency,unitPrice:RATES[currency],totalFiat:Number(total.toFixed(2)),walletAddress:wallet,paymentMethod:null,paymentReference:null,status:"PENDING_PAYMENT",proofPath:null,proofOriginalName:null,proofUploadedAt:null,processingDeadline:null,txid:null,createdAt:now,updatedAt:now,emailNotifications:true,emailLog:[]};db.addOrder(order);const emailResult=await notify(order,"ORDER_CREATED","コイン — Order received "+order.reference,"Order received",`<p>Your order <b>${esc(order.reference)}</b> has been created successfully.</p>${orderDetailsHtml(order)}<p>Your order is waiting for payment. Keep this email. The tracking button below lets you follow the order without keeping the website open.</p>`);const saved=db.getOrder(order.reference);res.json({success:true,order:publicOrder(saved),email:{sent:emailResult.sent,reason:emailResult.sent?null:emailResult.reason}})});
router.get("/:reference/payment-details",(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});const method=String(req.query.method||"").toUpperCase();if(!allowed(o.currency,method))return res.status(400).json({success:false,message:"Payment method is not available for this currency."});const d=PAYMENT_DETAILS[method];if(!d)return res.status(404).json({success:false,message:"Payment details are not configured."});res.json({success:true,method,details:d,testing:Boolean((d.values||[]).some(v=>String(v).includes("TEST")||String(v).includes("000000")))})});
router.get("/:reference",(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});res.json({success:true,order:publicOrder(o),serverNow:new Date().toISOString()})});
router.post("/:reference/proof",upload.single("proof"),(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"Proof can only be uploaded while payment is pending."});if(!req.file)return res.status(400).json({success:false,message:"Upload a JPG, PNG, WEBP or PDF proof up to 5MB."});const updated=db.updateOrder(o.reference,{proofPath:req.file.path,proofOriginalName:req.file.originalname,proofUploadedAt:new Date().toISOString()});res.json({success:true,order:publicOrder(updated)})});
router.post("/:reference/payment-reported",async(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});const method=String(req.body.paymentMethod||"").toUpperCase();if(!allowed(o.currency,method))return res.status(400).json({success:false,message:"Payment method is not available for this currency."});if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"This order is no longer waiting for payment."});const paymentReference=String(req.body.paymentReference||"").trim();if(method==="MPESA"){if(!paymentReference)return res.status(400).json({success:false,message:"M-Pesa transaction ID is required."});}else if(!o.proofPath||!fs.existsSync(o.proofPath)){return res.status(400).json({success:false,message:"Payment proof is required for this payment method."});}const reportedAt=new Date().toISOString(),deadline=new Date(Date.now()+20*60*1000).toISOString(),updated=db.updateOrder(o.reference,{paymentMethod:method,paymentReference:paymentReference||null,status:"PAYMENT_REPORTED",processingDeadline:deadline,paymentReportedAt:reportedAt});const emailResult=await notify(updated,"PAYMENT_REPORTED","コイン — Payment received for review "+o.reference,"Payment reported",`<p>We received your payment report for <b>${esc(o.reference)}</b>.</p>${orderDetailsHtml(updated)}<p>Our team will verify the payment manually. The estimated processing window is <b>20 minutes</b>.</p><p>You can close the site now. We will email you when the payment is confirmed and again when the USDT transfer is completed.</p>`);const finalOrder=db.getOrder(o.reference);res.json({success:true,order:publicOrder(finalOrder),email:{sent:emailResult.sent,provider:emailResult.provider||null,reason:emailResult.sent?null:emailResult.reason}})});
module.exports={router,RATES,FEES,METHODS,proofDir,sendEmail,publicOrder,emailLayout,notify,orderDetailsHtml,recordEmail};
