require("dotenv").config();
"use strict";
const express=require("express");
const multer=require("multer");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const db=require("./database");
const limits=require("./limits");
const customers=require("./customers");const offers=require("./offers");
const router=express.Router();
const createAttempts=new Map();
function allowCreate(ip){const now=Date.now(),x=createAttempts.get(ip)||{n:0,t:now};if(now-x.t>15*60*1000){x.n=0;x.t=now}x.n++;createAttempts.set(ip,x);return x.n<=25}
const DEFAULT_RATES={MZN:65,AOA:950,ZAR:18.5,USD:1.02};
const FEES={TRC20:5,BEP20:3,ERC20:5,POLYGON:3,SOLANA:3};
function minimumUSDT(network){const mins={TRC20:80,BEP20:200,ERC20:50,POLYGON:120,SOLANA:140};return mins[network]??50}
const METHODS={MZN:["MPESA","ABSA","STANDARD_BANK","PAYPAL"],AOA:["BANK_TRANSFER","PAYPAL"],ZAR:["PAYPAL","STANDARD_BANK","ABSA"],USD:["CARD","PAYPAL"]};
const PAYMENT_DETAILS={
 MPESA:{label:"M-Pesa",title:"M-Pesa payment",fields:["Name","Number"],values:[process.env.MPESA_NAME||"KOIN TEST",process.env.MPESA_NUMBER||"84 000 0000"],instruction:"Send the exact total shown for your order, then enter the M-Pesa transaction ID below. No screenshot is required."},
 ABSA:{label:"ABSA",title:"ABSA bank transfer",fields:["Account name","Account number","Branch"],values:[process.env.ABSA_ACCOUNT_NAME||"KOIN TEST",process.env.ABSA_ACCOUNT||"0000000000",process.env.ABSA_BRANCH||"0000"],instruction:"Make the transfer using the details above, then upload your payment proof."},
 PAYPAL:{label:"PayPal",title:"PayPal payment",fields:["PayPal email"],values:[process.env.PAYPAL_EMAIL||"payments@example.com"],instruction:"Complete the payment to the PayPal account above, then upload your payment proof."},
 BANK_TRANSFER:{label:"Multicaixa / EMIS",title:"Multicaixa / EMIS",fields:["Entity","Reference"],values:[process.env.MULTICAIXA_ENTITY||"00000",process.env.MULTICAIXA_REFERENCE||"KOIN-TEST"],instruction:"Complete the payment with the entity and reference above, then upload your payment proof."},
 STANDARD_BANK:{label:"Standard Bank",title:"Standard Bank transfer",fields:["Account name","Account number","Branch"],values:[process.env.STANDARD_BANK_ACCOUNT_NAME||"KOIN TEST",process.env.STANDARD_BANK_ACCOUNT||"0000000000",process.env.STANDARD_BANK_BRANCH||"0000"],instruction:"Make the transfer using the details above, then upload your payment proof."},
 CARD:{label:"Card",title:"Card payment",fields:["Payment page"],values:[process.env.CARD_PAYMENT_URL||"Payment gateway not configured"],instruction:"Complete the card payment through the configured gateway, then upload your payment proof."}
};
const proofDir=path.join(__dirname,"uploads","proofs");
fs.mkdirSync(proofDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,proofDir),filename:(_,file,cb)=>cb(null,Date.now()+"-"+crypto.randomBytes(6).toString("hex")+path.extname(file.originalname).toLowerCase())}),limits:{fileSize:5*1024*1024},fileFilter:(_,file,cb)=>cb(null,["image/jpeg","image/png","image/webp","application/pdf"].includes(file.mimetype))});
function ref(){return "KOIN-"+new Date().toISOString().slice(0,10).replace(/-/g,"")+"-"+crypto.randomBytes(3).toString("hex").toUpperCase()}
function publicOrder(o){if(!o)return null;const copy={...o};delete copy.proofPath;delete copy.emailLog;return copy}
function validWallet(network,w){w=String(w||"").trim();if(network==="TRC20")return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(w);if(["BEP20","ERC20","POLYGON"].includes(network))return /^0x[a-fA-F0-9]{40}$/.test(w);if(network==="SOLANA")return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(w);return false}
function allowed(currency,method){return METHODS[currency]?.includes(method)}
function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
const publicUrl=()=>String(process.env.PUBLIC_URL||process.env.RENDER_EXTERNAL_URL||"http://localhost:3000").replace(/\/$/,"");
function emailLayout(title,body,reference){
 const statusUrl=reference?`${publicUrl()}/status.html?reference=${encodeURIComponent(reference)}`:publicUrl();
 const safeUrl=esc(statusUrl);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#07090d;color:#eef2f7;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%"><div style="padding:28px 14px;background:radial-gradient(circle at 50% 0%,rgba(32,201,151,.12),transparent 42%),#07090d"><div style="width:100%;max-width:620px;margin:0 auto;background:#10151d;border:1px solid #26313d;border-radius:20px;overflow:hidden;box-shadow:0 18px 55px rgba(0,0,0,.35)">
 <div style="padding:22px 24px;border-bottom:1px solid #202a34;background:linear-gradient(135deg,#121a20,#0e1319)">
  <div style="display:flex;align-items:center;gap:10px">
   <div style="width:42px;height:42px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#24d7a3,#119b77);border:2px solid rgba(255,255,255,.14);box-shadow:0 0 24px rgba(32,201,151,.22);color:#04120d;font-size:19px;font-weight:900">コ</div>
   <div><div style="font-size:19px;line-height:1;font-weight:900;letter-spacing:.2px;color:#f5f7fa">コイン</div><div style="font-size:10px;color:#7f8a98;margin-top:4px;letter-spacing:1.2px;text-transform:uppercase">USDT • Order service</div></div>
  </div>
 </div>
 <div style="padding:26px 24px 24px"><div style="font-size:10px;color:#20c997;font-weight:900;letter-spacing:1.5px;text-transform:uppercase;margin-bottom:8px">Order update</div><h1 style="margin:0;font-size:25px;line-height:1.2;color:#f4f7fa">${esc(title)}</h1>${body}<div style="margin:24px 0 8px"><a href="${safeUrl}" style="display:inline-block;background:#20c997;color:#04130e;text-decoration:none;font-weight:900;font-size:12px;padding:13px 18px;border-radius:11px">Track your order&nbsp; →</a></div><div style="font-size:11px;line-height:1.6;color:#687483;word-break:break-all">If the button does not open, use this link:<br><a href="${safeUrl}" style="color:#20c997;text-decoration:none">${safeUrl}</a></div></div>
 <div style="padding:15px 24px;border-top:1px solid #202a34;background:#0c1117;color:#687483;font-size:10px;line-height:1.55">This is an automated message from コイン. Keep your order reference for support. Never share wallet private keys or passwords.</div>
 </div></div></body></html>`;
}
function orderDetailsHtml(o){return `<div style="margin:18px 0;padding:16px;background:#0b1017;border:1px solid #26323e;border-radius:12px"><p style="margin:4px 0"><b>Order:</b> ${esc(o.reference)}</p><p style="margin:4px 0"><b>Customer:</b> ${esc(o.customerName)}</p><p style="margin:4px 0"><b>Amount:</b> ${esc(o.amountUSDT)} USDT</p><p style="margin:4px 0"><b>Network:</b> ${esc(o.network)}</p><p style="margin:4px 0"><b>Network fee:</b> ${esc(o.networkFeeUSDT)} USDT</p><p style="margin:4px 0"><b>USDT price:</b> ${esc(o.unitPrice)} ${esc(o.currency)} / USDT</p><p style="margin:4px 0"><b>Total to pay:</b> ${esc(o.totalFiat)} ${esc(o.currency)}</p><p style="margin:4px 0;word-break:break-all"><b>Receiving wallet:</b> ${esc(o.walletAddress)}</p>${o.paymentMethod?`<p style="margin:4px 0"><b>Payment method:</b> ${esc(o.paymentMethod)}</p>`:""}${o.paymentReference?`<p style="margin:4px 0"><b>Payment reference:</b> ${esc(o.paymentReference)}</p>`:""}</div>`}
async function sendEmail(to,subject,html){
 const recipient=String(to||"").trim(),apiKey=String(process.env.RESEND_API_KEY||"").trim(),from=String(process.env.MAIL_FROM||"").trim();
 if(!recipient)return {sent:false,reason:"missing_recipient"};
 if(!apiKey||!from||apiKey.startsWith("re_xxxxxxxxx")){console.error("[EMAIL] NOT CONFIGURED — set a real RESEND_API_KEY and MAIL_FROM.");return {sent:false,reason:"email_not_configured"};}
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{const r=await fetch("https://api.resend.com/emails",{method:"POST",signal:controller.signal,headers:{Authorization:"Bearer "+apiKey,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject,html})});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(`Resend ${r.status}: ${data?.message||data?.error||raw||"Unknown provider error"}`);console.log(`[EMAIL] SENT to ${recipient}: ${subject} (${data.id||"no-id"})`);return {sent:true,id:data.id||null};}catch(e){const reason=e?.name==="AbortError"?"Email provider timeout after 15s":e?.message||"Unknown email error";console.error(`[EMAIL] FAILED to ${recipient}: ${reason}`);return {sent:false,reason}}finally{clearTimeout(timer)}}
function recordEmail(reference,event,result){const o=db.getOrder(reference);if(!o)return null;const log=Array.isArray(o.emailLog)?o.emailLog.slice(-19):[];log.push({event,status:result.sent?"SENT":"FAILED",id:result.id||null,error:result.sent?null:result.reason,at:new Date().toISOString()});return db.updateOrder(reference,{lastEmailStatus:result.sent?"SENT":"FAILED",lastEmailError:result.sent?null:result.reason,lastEmailAt:new Date().toISOString(),emailLog:log})}
async function notify(o,event,subject,title,body){const result=await sendEmail(o.customerEmail,subject,emailLayout(title,body,o.reference));recordEmail(o.reference,event,result);return result}
router.post("/",async(req,res)=>{if(!allowCreate(req.ip||"unknown"))return res.status(429).json({success:false,message:"Too many order attempts from this connection. Please wait a few minutes and try again."});const b=req.body||{},currency=String(b.currency||"").toUpperCase(),network=String(b.network||"").toUpperCase(),amount=Number(b.amountUSDT),email=String(b.email||"").trim().toLowerCase(),name=String(b.name||"").trim(),wallet=String(b.walletAddress||b.wallet||"").trim(),offerId=String(b.offerId||"").trim();const currentRates=limits.currentRates(); if(!currentRates[currency]||!FEES[network])return res.status(400).json({success:false,message:"Currency or network is invalid."});const minimum=minimumUSDT(network);if(!Number.isFinite(amount)||amount<minimum||amount>100000)return res.status(400).json({success:false,message:`Minimum purchase for ${network} is ${minimum.toFixed(0)} USDT. Maximum is 100,000 USDT.`});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({success:false,message:"A valid email is required."});if(!validWallet(network,wallet))return res.status(400).json({success:false,message:"Wallet address does not match the selected network."});
const policy=limits.get(),orders=db.readOrders(),since=Date.now()-24*60*60*1000,normalized=customers.key(email);
const customer24=orders.filter(o=>String(o.customerEmail||"").toLowerCase()===normalized&&Date.parse(o.createdAt||0)>=since);
const active=orders.filter(o=>String(o.customerEmail||"").toLowerCase()===normalized&&["PENDING_PAYMENT","PAYMENT_REPORTED","PAID"].includes(o.status));
const site24=orders.filter(o=>Date.parse(o.createdAt||0)>=since);
const customerVolume=customer24.reduce((sum,o)=>sum+Number(o.amountUSDT||0),0);
if(policy.orderLimitsEnabled){
 if(policy.maxActiveOrdersPerCustomer>0&&active.length>=policy.maxActiveOrdersPerCustomer)return res.status(429).json({success:false,message:`You already have ${active.length} active order(s). Please finish or close an existing order before creating another.`});
 if(policy.maxOrdersPerCustomer24h>0&&customer24.length>=policy.maxOrdersPerCustomer24h)return res.status(429).json({success:false,message:`Order limit reached: maximum ${policy.maxOrdersPerCustomer24h} orders per customer in 24 hours.`});
 if(policy.maxUSDTPerCustomer24h>0&&customerVolume+amount>policy.maxUSDTPerCustomer24h)return res.status(429).json({success:false,message:`Customer 24-hour volume limit reached. Maximum is ${policy.maxUSDTPerCustomer24h.toLocaleString()} USDT.`});
 const sameAmount=customer24.filter(o=>Math.abs(Number(o.amountUSDT||0)-amount)<0.0000001);
 if(policy.maxSameAmountPerCustomer24h>0&&sameAmount.length>=policy.maxSameAmountPerCustomer24h)return res.status(429).json({success:false,message:`This amount has already been used ${sameAmount.length} time(s) in the last 24 hours. Please choose a different amount.`});
 if(policy.maxSiteOrders24h>0&&site24.length>=policy.maxSiteOrders24h)return res.status(503).json({success:false,message:"The platform has reached its 24-hour order capacity. Please try again later."});
}
let unitPrice=currentRates[currency],appliedOffer=null;if(offerId){const ctx=b.offerContext||{};appliedOffer=offers.getOffer(offerId,{country:String(ctx.country||currency).toUpperCase(),offerNeed:String(ctx.offerNeed||"buy"),firstTime:String(ctx.firstTime||"any"),useCase:String(ctx.useCase||"any")});if(!appliedOffer||appliedOffer.currency!==currency)return res.status(400).json({success:false,message:"The selected offer is no longer available for this market."});unitPrice=Number(appliedOffer.price);}const fee=FEES[network],total=(amount+fee)*unitPrice,now=new Date().toISOString(),customer=customers.touch(email,name);const order={id:crypto.randomUUID(),reference:ref(),customerId:customer?.id||null,offerId:appliedOffer?.id||null,offerTitle:appliedOffer?.title||null,customerName:name||"Customer",customerEmail:email,amountUSDT:amount,network,networkFeeUSDT:fee,currency,unitPrice,totalFiat:Number(total.toFixed(2)),walletAddress:wallet,paymentMethod:null,paymentReference:null,status:"PENDING_PAYMENT",proofPath:null,proofOriginalName:null,proofUploadedAt:null,processingDeadline:null,txid:null,createdAt:now,updatedAt:now,emailNotifications:true,emailLog:[]};db.addOrder(order);customers.recordOrder(email,name,amount,"PENDING_PAYMENT",order.createdAt);const emailResult=await notify(order,"ORDER_CREATED","コイン — Order received "+order.reference,"Order received",`<p>Your order <b>${esc(order.reference)}</b> has been created successfully.</p>${orderDetailsHtml(order)}<p>Your order is waiting for payment. Keep this email. The tracking button below lets you follow the order without keeping the website open.<br><span style="font-size:11px;color:#7d8996">This order is associated with your KOIN customer activity and applicable purchase limits.</span></p>`);const saved=db.getOrder(order.reference);res.json({success:true,order:publicOrder(saved),email:{sent:emailResult.sent,reason:emailResult.sent?null:emailResult.reason}})});
router.post("/:reference/cancel",(req,res)=>{
 const o=db.getOrder(req.params.reference); if(!o)return res.status(404).json({success:false,message:"Order not found."});
 if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"Only unpaid orders can be cancelled."});
 if(o.proofPath&&fs.existsSync(o.proofPath)){try{fs.unlinkSync(o.proofPath)}catch{}}
 const updated=db.updateOrder(o.reference,{status:"CANCELLED",cancelledAt:new Date().toISOString(),proofPath:null,proofOriginalName:null,proofUploadedAt:null});
 res.json({success:true,order:publicOrder(updated)});
});
router.post("/:reference/currency",(req,res)=>{
 const o=db.getOrder(req.params.reference);
 if(!o)return res.status(404).json({success:false,message:"Order not found."});
 if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"Currency can only be changed before payment is reported."});
 const currency=String(req.body.currency||"").toUpperCase();
 const currentRates=limits.currentRates(); if(!currentRates[currency])return res.status(400).json({success:false,message:"Currency is not supported."});
 if(currency===o.currency)return res.json({success:true,order:publicOrder(o)});
 if(o.proofPath&&fs.existsSync(o.proofPath)){try{fs.unlinkSync(o.proofPath)}catch{}}
 const total=(Number(o.amountUSDT)+Number(o.networkFeeUSDT))*currentRates[currency];
 const updated=db.updateOrder(o.reference,{currency,unitPrice:currentRates[currency],totalFiat:Number(total.toFixed(2)),paymentMethod:null,paymentReference:null,proofPath:null,proofOriginalName:null,proofUploadedAt:null,offerId:null,offerTitle:null});
 res.json({success:true,order:publicOrder(updated)});
});
router.get("/:reference/payment-details",(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});const method=String(req.query.method||"").toUpperCase();if(!allowed(o.currency,method))return res.status(400).json({success:false,message:"Payment method is not available for this currency."});const d=PAYMENT_DETAILS[method];if(!d)return res.status(404).json({success:false,message:"Payment details are not configured."});res.json({success:true,method,details:d,testing:Boolean((d.values||[]).some(v=>String(v).includes("TEST")||String(v).includes("000000")))})});
router.get("/:reference",(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});res.json({success:true,order:publicOrder(o),serverNow:new Date().toISOString()})});
router.post("/:reference/proof",upload.single("proof"),(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"Proof can only be uploaded while payment is pending."});if(!req.file)return res.status(400).json({success:false,message:"Upload a JPG, PNG, WEBP or PDF proof up to 5MB."});const updated=db.updateOrder(o.reference,{proofPath:req.file.path,proofOriginalName:req.file.originalname,proofUploadedAt:new Date().toISOString()});res.json({success:true,order:publicOrder(updated)})});
router.post("/:reference/payment-reported",async(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});const method=String(req.body.paymentMethod||"").toUpperCase();if(!allowed(o.currency,method))return res.status(400).json({success:false,message:"Payment method is not available for this currency."});if(o.status!=="PENDING_PAYMENT")return res.status(400).json({success:false,message:"This order is no longer waiting for payment."});const paymentReference=String(req.body.paymentReference||"").trim();if(method==="MPESA"){if(!paymentReference)return res.status(400).json({success:false,message:"M-Pesa transaction ID is required."});}else if(!o.proofPath||!fs.existsSync(o.proofPath)){return res.status(400).json({success:false,message:"Payment proof is required for this payment method."});}const reportedAt=new Date().toISOString(),deadline=new Date(Date.now()+20*60*1000).toISOString(),updated=db.updateOrder(o.reference,{paymentMethod:method,paymentReference:paymentReference||null,status:"PAYMENT_REPORTED",processingDeadline:deadline,paymentReportedAt:reportedAt});const emailResult=await notify(updated,"PAYMENT_REPORTED","コイン — Payment received for review "+o.reference,"Payment reported",`<p>We received your payment report for <b>${esc(o.reference)}</b>.</p>${orderDetailsHtml(updated)}<p>Our team will verify the payment manually. The estimated processing window is <b>20 minutes</b>.</p><p>You can close the site now. We will email you when the payment is confirmed and again when the USDT transfer is completed.</p>`);const finalOrder=db.getOrder(o.reference);res.json({success:true,order:publicOrder(finalOrder),email:{sent:emailResult.sent,provider:emailResult.provider||null,reason:emailResult.sent?null:emailResult.reason}})});
module.exports={router,RATES:DEFAULT_RATES,FEES,METHODS,minimumUSDT,proofDir,sendEmail,publicOrder,emailLayout,notify,orderDetailsHtml,recordEmail};
