require("dotenv").config();
"use strict";
const express=require("express");const path=require("path");const fs=require("fs");const crypto=require("crypto");
const db=require("./database");
const storage=require("./storage");
const community=require("./community");
const customers=require("./customers");
const limits=require("./limits");const offers=require("./offers");const onboarding=require("./onboarding");const {router:ordersRouter,publicOrder,sendEmail,emailLayout,notify,orderDetailsHtml,recordEmail}=require("./orders");
const app=express();const PORT=Number(process.env.PORT||3000);
app.disable("x-powered-by");app.set("trust proxy",1);app.use(express.json({limit:"100kb"}));app.use(express.urlencoded({extended:true}));
const ADMIN_USER=process.env.ADMIN_USERNAME||"Jay";const ADMIN_PASS=process.env.ADMIN_PASSWORD||"";const ADMIN_HASH=process.env.ADMIN_PASSWORD_HASH||"";const SESSION_SECRET=process.env.ADMIN_SESSION_SECRET||"";const COOKIE="koin_admin_session";const attempts=new Map();
function b64(x){return Buffer.from(x).toString("base64url")}function signSession(user){const payload=b64(JSON.stringify({u:user,e:Date.now()+8*60*60*1000}));const sig=crypto.createHmac("sha256",SESSION_SECRET).update(payload).digest("base64url");return payload+"."+sig}function verifySession(token){try{const [p,s]=String(token||"").split(".");if(!p||!s||!SESSION_SECRET)return false;const good=crypto.createHmac("sha256",SESSION_SECRET).update(p).digest("base64url");if(s.length!==good.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(good)))return false;const data=JSON.parse(Buffer.from(p,"base64url").toString());return data.u===ADMIN_USER&&Number(data.e)>Date.now()}catch{return false}}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||"").split(";").filter(Boolean).map(x=>{const i=x.indexOf("=");return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function adminAuth(req,res,next){if(verifySession(cookies(req)[COOKIE]))return next();return res.status(401).json({success:false,message:"Admin authentication required."})}
function adminPage(req,res){if(verifySession(cookies(req)[COOKIE]))return res.sendFile(path.join(__dirname,"admin.html"));return res.redirect("/admin-login.html")}
function rateLimitLogin(ip){const now=Date.now(),x=attempts.get(ip)||{n:0,t:now};if(now-x.t>15*60*1000){x.n=0;x.t=now}x.n++;attempts.set(ip,x);return x.n<=10}
app.post("/api/admin/login",(req,res)=>{const ip=req.ip||"unknown";if(!rateLimitLogin(ip))return res.status(429).json({success:false,message:"Too many login attempts. Try again later."});const user=String(req.body.username||""),pass=String(req.body.password||"");if(!SESSION_SECRET||(!ADMIN_HASH&&!ADMIN_PASS))return res.status(503).json({success:false,message:"Admin credentials are not configured on the server."});const okUser=user===ADMIN_USER;let okPass=false;if(ADMIN_HASH){try{const [salt,hex]=ADMIN_HASH.split("$");const stored=Buffer.from(hex,"hex");const derived=crypto.scryptSync(pass,salt,stored.length);okPass=derived.length===stored.length&&crypto.timingSafeEqual(derived,stored)}catch{okPass=false}}else{const pb=Buffer.from(pass),ab=Buffer.from(ADMIN_PASS);okPass=pb.length===ab.length&&crypto.timingSafeEqual(pb,ab)}if(!okUser||!okPass)return res.status(401).json({success:false,message:"Invalid admin credentials."});res.setHeader("Set-Cookie",`${COOKIE}=${encodeURIComponent(signSession(user))}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${8*60*60}${process.env.NODE_ENV==="production"?"; Secure":""}`);res.json({success:true})});
app.post("/api/admin/logout",(req,res)=>{res.setHeader("Set-Cookie",`${COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${process.env.NODE_ENV==="production"?"; Secure":""}`);res.json({success:true})});
app.get("/api/admin/session",(req,res)=>res.json({success:true,authenticated:verifySession(cookies(req)[COOKIE])}));

app.use("/api/orders",ordersRouter);
app.get("/api/community/messages",(req,res)=>{res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");const room=String(req.query.room||"general").slice(0,100);res.json({success:true,room,messages:community.listMessages(room)});});
app.post("/api/community/messages",(req,res)=>{const text=String(req.body.text||"").trim();const name=String(req.body.name||"Guest").trim()||"Guest";const room=String(req.body.room||"general").slice(0,100);if(!text)return res.status(400).json({success:false,message:"Message is required."});res.json({success:true,message:community.addMessage({room,name,text})});});
app.get("/api/community/offers",(req,res)=>{res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");res.json({success:true,offers:community.listOffers()})});
app.post("/api/community/offers",(req,res)=>{try{const offer=community.addOffer(req.body||{});res.json({success:true,offer});}catch(e){res.status(400).json({success:false,message:e.message||"Invalid offer."});}});
app.delete("/api/community/offers/:id",adminAuth,(req,res)=>{const offer=community.removeOffer(req.params.id);if(!offer)return res.status(404).json({success:false,message:"Offer not found."});res.json({success:true});});
app.get("/api/config",(req,res)=>{res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");res.json({success:true,rates:limits.currentRates(),rateVersion:limits.rateVersion(),nextRateSchedule:limits.nextSchedule(),updatedAt:new Date().toISOString()})});
app.get("/api/offers/config",(req,res)=>{const s=offers.get();res.set("Cache-Control","no-store");res.json({success:true,settings:{enabled:s.enabled,rotateOnRefresh:s.rotateOnRefresh,requireOnboarding:s.requireOnboarding,supportUrl:s.supportUrl,version:s.version||1}});});
app.get("/api/offers/recommend",(req,res)=>{res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");const answers={country:String(req.query.country||""),offerNeed:String(req.query.offerNeed||""),firstTime:String(req.query.firstTime||""),useCase:String(req.query.useCase||"")};const seed=Math.max(0,Number(req.query.seed)||0);res.json({success:true,enabled:offers.get().enabled,rotateOnRefresh:offers.get().rotateOnRefresh,offers:offers.recommend(answers,seed)})});
app.post("/api/onboarding",(req,res)=>{try{const visitor=onboarding.save(req.body||{});const cfg=offers.get();res.json({success:true,visitor,offersEnabled:Boolean(cfg.enabled),offers:offers.recommend(req.body||{},0)})}catch(e){res.status(400).json({success:false,message:e.message||"Invalid onboarding."})}});
app.get("/api/admin/offers",adminAuth,(req,res)=>{const s=offers.get();res.json({success:true,settings:{enabled:s.enabled,rotateOnRefresh:s.rotateOnRefresh,requireOnboarding:s.requireOnboarding,supportUrl:s.supportUrl,version:s.version||1},offers:(s.offers||[]).slice().reverse()})});
app.put("/api/admin/offers/settings",adminAuth,(req,res)=>res.json({success:true,settings:offers.settings(req.body||{})}));
app.post("/api/admin/offers",adminAuth,(req,res)=>{try{
 const body=req.body||{}, offer=offers.add(body); let announcement=null;
 if(body.announceOnStart && offer.startAt){
   const start=new Date(offer.startAt);
   if(start>new Date()){announcement=limits.addAnnouncement(body.announcementText||`${offer.title} is now available at ${offer.price} ${offer.currency} / USDT.`,{kind:"scheduled",startAt:start.toISOString(),endAt:new Date(start.getTime()+24*60*60*1000).toISOString(),repeatEveryMinutes:0,supportUrl:offers.get().supportUrl});}
 }
 res.json({success:true,offer,announcement});
}catch(e){res.status(400).json({success:false,message:e.message||"Invalid offer."})}});
app.put("/api/admin/offers/:id",adminAuth,(req,res)=>{try{const item=offers.updateOffer(req.params.id,req.body||{});if(!item)return res.status(404).json({success:false,message:"Offer not found."});res.json({success:true,offer:item})}catch(e){res.status(400).json({success:false,message:e.message||"Invalid offer."})}});
app.delete("/api/admin/offers/:id",adminAuth,(req,res)=>{const item=offers.remove(req.params.id);if(!item)return res.status(404).json({success:false,message:"Offer not found."});res.json({success:true})});
app.get("/api/admin/onboarding",adminAuth,(req,res)=>res.json({success:true,visitors:onboarding.list()}));
app.get("/api/admin/settings",adminAuth,(req,res)=>res.json({success:true,settings:limits.get()}));
app.put("/api/admin/rates",adminAuth,(req,res)=>{try{const rates=limits.setRates(req.body||{});res.json({success:true,rates,updatedAt:new Date().toISOString()})}catch(e){res.status(400).json({success:false,message:e.message||"Invalid rates."})}});
app.get("/api/admin/rate-schedules",adminAuth,(req,res)=>res.json({success:true,schedules:limits.get().rateSchedules||[]}));
app.post("/api/admin/rate-schedules",adminAuth,(req,res)=>{try{
 const body=req.body||{}; const item=limits.addRateSchedule(body);
 let announcement=null;
 if(String(body.announcement||"").trim()){
   const start=new Date(item.effectiveAt); const end=new Date(start.getTime()+Number(item.popupDurationMinutes||1440)*60000);
   announcement=limits.addAnnouncement(String(body.announcement).trim(),{kind:"scheduled",startAt:start.toISOString(),endAt:end.toISOString(),repeatEveryMinutes:0,supportUrl:limits.get().supportUrl||"contact.html"});
 }
 res.json({success:true,schedule:item,announcement});
}catch(e){res.status(400).json({success:false,message:e.message||"Invalid schedule."})}});
app.delete("/api/admin/rate-schedules/:id",adminAuth,(req,res)=>{const item=limits.removeRateSchedule(req.params.id);if(!item)return res.status(404).json({success:false,message:"Schedule not found."});res.json({success:true})});
app.post("/api/admin/announcements",adminAuth,(req,res)=>{try{const body=req.body||{}; const instant=body.kind==='instant'; const item=limits.addAnnouncement(body.text,{kind:instant?'instant':'scheduled',startAt:instant?new Date().toISOString():body.startAt,endAt:instant?new Date('2099-12-31T23:59:59Z').toISOString():body.endAt,repeatEveryMinutes:instant?0:body.repeatEveryMinutes});res.json({success:true,announcement:item})}catch(e){res.status(400).json({success:false,message:e.message||"Invalid announcement."})}});
app.get("/api/announcements",(req,res)=>{res.set("Cache-Control","no-store");const s=limits.get(),now=Date.now();const items=(s.announcements||[]).filter(x=>Date.parse(x.startAt||x.at||0)<=now && Date.parse(x.endAt||"2999-01-01")>=now).slice(-20);res.json({success:true,announcements:items,nextRateSchedule:limits.nextSchedule(now)})});
app.put("/api/admin/settings",adminAuth,(req,res)=>res.json({success:true,settings:limits.update(req.body||{})}));
app.get("/api/admin/customers",adminAuth,(req,res)=>{const orders=db.readOrders();const list=customers.list(orders).map(c=>{const mine=orders.filter(o=>customers.key(o.customerEmail)===c.email);const since=Date.now()-86400000;return {...c,orders24h:mine.filter(o=>Date.parse(o.createdAt||0)>=since).length,usdt24h:mine.filter(o=>Date.parse(o.createdAt||0)>=since).reduce((n,o)=>n+Number(o.amountUSDT||0),0),activeOrders:mine.filter(o=>["PENDING_PAYMENT","PAYMENT_REPORTED","PAID"].includes(o.status)).length}});res.json({success:true,customers:list})});
app.get("/api/health",(_,res)=>res.json({success:true,service:"コイン",status:"online",emailConfigured:Boolean((process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS&&process.env.MAIL_FROM)||(process.env.RESEND_API_KEY&&process.env.MAIL_FROM&&!String(process.env.RESEND_API_KEY).startsWith("re_xxxxxxxxx"))),publicUrl:process.env.PUBLIC_URL||null,adminAuthConfigured:Boolean(process.env.ADMIN_USERNAME&&((process.env.ADMIN_PASSWORD_HASH)||(process.env.ADMIN_PASSWORD))&&process.env.ADMIN_SESSION_SECRET),dataDir:storage.DATA_DIR,storageConfigured:Boolean(process.env.DATA_DIR),time:new Date().toISOString()}));
app.get("/api/admin/orders",adminAuth,(_,res)=>{const orders=db.readOrders().map(o=>({...publicOrder(o),hasProof:Boolean(o.proofPath),proofOriginalName:o.proofOriginalName||null,proofUploadedAt:o.proofUploadedAt||null,emailHistory:Array.isArray(o.emailLog)?o.emailLog.slice(-10):[]}));res.json({success:true,orders})});
app.get("/api/admin/orders/:reference/proof",adminAuth,(req,res)=>{const o=db.getOrder(req.params.reference);if(!o||!o.proofPath)return res.status(404).send("Proof not found");if(!fs.existsSync(o.proofPath))return res.status(404).send("Proof file not found");res.sendFile(path.resolve(o.proofPath))});
async function adminEmailUpdate(reference,event,subject,title,body){const o=db.getOrder(reference);if(!o)return {sent:false,reason:"order_not_found"};const result=await notify(o,event,subject,title,body);return {sent:result.sent,reason:result.sent?null:result.reason,id:result.id||null}}
app.post("/api/admin/orders/:reference/confirm-payment",adminAuth,async(req,res)=>{const o=db.getOrder(req.params.reference);if(!o||o.status!=="PAYMENT_REPORTED")return res.status(400).json({success:false,message:"Order must be PAYMENT_REPORTED."});const updated=db.updateOrder(o.reference,{status:"PAID",paymentConfirmedAt:new Date().toISOString()});const e=await adminEmailUpdate(o.reference,"PAYMENT_CONFIRMED","コイン — Payment confirmed "+o.reference,"Payment confirmed",`<p>Your payment for <b>${o.reference}</b> has been verified.</p>${orderDetailsHtml(updated)}<p>Your USDT transfer is now being prepared. You can close the website; we will email you again when the transfer is completed.</p>`);res.json({success:true,order:publicOrder(db.getOrder(o.reference)),email:e})});
app.post("/api/admin/orders/:reference/mark-sent",adminAuth,async(req,res)=>{const txid=String(req.body.txid||"").trim();if(!txid)return res.status(400).json({success:false,message:"TXID is required."});const o=db.getOrder(req.params.reference);if(!o||o.status!=="PAID")return res.status(400).json({success:false,message:"Order must be PAID before completion."});const updated=db.updateOrder(o.reference,{status:"COMPLETED",txid,completedAt:new Date().toISOString()});const explorer={TRC20:`https://tronscan.org/#/transaction/${encodeURIComponent(txid)}`,BEP20:`https://bscscan.com/tx/${encodeURIComponent(txid)}`,ERC20:`https://etherscan.io/tx/${encodeURIComponent(txid)}`,POLYGON:`https://polygonscan.com/tx/${encodeURIComponent(txid)}`,SOLANA:`https://solscan.io/tx/${encodeURIComponent(txid)}`}[o.network];const e=await adminEmailUpdate(o.reference,"ORDER_COMPLETED","コイン — Order completed "+o.reference,"Order completed",`<p>Your order <b>${o.reference}</b> is complete.</p>${orderDetailsHtml(updated)}<p><b>${o.amountUSDT} USDT</b> was sent via <b>${o.network}</b> to your receiving wallet.</p><p style="word-break:break-all"><b>TXID:</b> ${String(txid).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}</p>${explorer?`<p><a href="${explorer}" style="color:#20c997">View transaction on blockchain explorer</a></p>`:""}`);res.json({success:true,order:publicOrder(db.getOrder(o.reference)),email:e})});
app.post("/api/admin/orders/:reference/resend-last",adminAuth,async(req,res)=>{const o=db.getOrder(req.params.reference);if(!o)return res.status(404).json({success:false,message:"Order not found."});let subject="",title="",body="";if(o.status==="PENDING_PAYMENT"){subject=`コイン — Order received ${o.reference}`;title="Order received";body=`<p>Your order <b>${o.reference}</b> is waiting for payment.</p>${orderDetailsHtml(o)}`}else if(o.status==="PAYMENT_REPORTED"){subject=`コイン — Payment received for review ${o.reference}`;title="Payment reported";body=`<p>Your payment report for <b>${o.reference}</b> is under manual review.</p>${orderDetailsHtml(o)}<p>Estimated processing window: <b>20 minutes</b>.</p>`}else if(o.status==="PAID"){subject=`コイン — Payment confirmed ${o.reference}`;title="Payment confirmed";body=`<p>Your payment for <b>${o.reference}</b> has been verified.</p>${orderDetailsHtml(o)}<p>Your USDT transfer is being prepared.</p>`}else{const explorer={TRC20:`https://tronscan.org/#/transaction/${encodeURIComponent(o.txid||"")}`,BEP20:`https://bscscan.com/tx/${encodeURIComponent(o.txid||"")}`,ERC20:`https://etherscan.io/tx/${encodeURIComponent(o.txid||"")}`,POLYGON:`https://polygonscan.com/tx/${encodeURIComponent(o.txid||"")}`,SOLANA:`https://solscan.io/tx/${encodeURIComponent(o.txid||"")}`}[o.network];subject=`コイン — Order completed ${o.reference}`;title="Order completed";body=`<p>Your order <b>${o.reference}</b> is complete.</p>${orderDetailsHtml(o)}<p><b>${o.amountUSDT} USDT</b> was sent via <b>${o.network}</b>.</p><p><b>TXID:</b> ${String(o.txid||"")}</p>${explorer?`<p><a href="${explorer}">View transaction</a></p>`:""}`}const e=await adminEmailUpdate(o.reference,"MANUAL_RESEND",subject,title,body);res.status(e.sent?200:502).json({success:e.sent,email:e})});
app.post("/api/admin/email-test",adminAuth,async(req,res)=>{const reference=String(req.body.reference||"").trim(),o=reference?db.getOrder(reference):null,to=String(req.body.to||o?.customerEmail||"").trim();if(!to)return res.status(400).json({success:false,message:"Enter a recipient email or provide an order reference."});const subject="コイン — Email delivery test";const result=await sendEmail(to,subject,emailLayout("Email delivery test",`<p>This is a real delivery test from <b>コイン</b>.</p>${o?orderDetailsHtml(o):""}<p>If you received this message, customer email delivery is working.</p>`,o?.reference||null));if(o)recordEmail(o.reference,"EMAIL_TEST",result);res.status(result.sent?200:502).json({success:result.sent,email:{sent:result.sent,reason:result.sent?null:result.reason,id:result.id||null}})});
// Never expose uploaded payment proofs through the public static server.
app.use("/uploads",(_,res)=>res.status(404).send("Not found"));
app.get("/admin.html",adminPage);app.use(express.static(__dirname));app.get("/",(_,res)=>res.sendFile(path.join(__dirname,"index.html")));app.use((req,res)=>req.path.startsWith("/api/")?res.status(404).json({success:false,message:"Route not found."}):res.status(404).send("Page not found."));
app.listen(PORT,()=>console.log(`\nコイン\nCustomer: http://localhost:${PORT}\nAdmin:    http://localhost:${PORT}/admin.html\nHealth:   http://localhost:${PORT}/api/health\nEmail:    ${process.env.RESEND_API_KEY&&process.env.MAIL_FROM&&!String(process.env.RESEND_API_KEY).startsWith("re_xxxxxxxxx")?"CONFIGURED":"NOT CONFIGURED — add a real Resend key"}\n`));
